#  _____           _            _
# | ____|___  ___ | |_ ___ _ __(_) ___
# |  _| / __|/ _ \| __/ _ \ '__| |/ __|
# | |___\__ \ (_) | ||  __/ |  | | (__
# |_____|___/\___/ \__\___|_|  |_|\___|

# A private anti-cheat for PocketMine-MP made by @ethaniccc
# GitHub: https://www.github.com/ethaniccc

#  Copyright (C) Ethaniccc - All Rights Reserved
#  Unauthorized copying of this file, via any medium is strictly prohibited
#  Proprietary and confidential
#  Written by Benjamin <schooldocumentsandstuff@gmail.com>, March, 2021

# Prefix for the anti-cheat when sending warnings.
prefix: "§l§6Eso§fteric§7>§r"
# Alert cooldown
alert_cooldown: 4

# Tags: {prefix}, {player}, {check_name}, {check_subtype}, {violations}, {data}
alert_message: "{prefix} §e{player} §7failed §e{check_name} ({check_subtype}) §7(§cx{violations}§7) §7[{data}§7]"

# Tags: {prefix}, {code}, {expires} < ban only
kick_message: "{prefix} Kicked (code={code})\nContact staff with a screenshot of this message if this issue persists"
ban_message: "{prefix} Banned (code={code})\nMake a ticket with a screenshot of this message if this is a mistake\nExpires: {expires}"

# Length in days to ban the player for, leave as "p" for permanent, this will only work if the punishment type is set to "ban"
ban_length: 7

# Message to broadcast when a player is banned, leave as "none" to disable
# Tags: {prefix}, {player}, {check_name}, {code_name}, {violations}, {expires}
ban_broadcast: "none"
# Message to broadcast when a player is kicked, leave as "none" to disable
# Tags: {prefix}, {player}, {check_name}, {code_name}, {violations}
kick_broadcast: "none"

# Setback types: smooth, instant, or none
setback_type: "none"

# Timeout settings
timeout:
  # If this is disabled, hackers may be able to disable Esoteric by cancelling the sending of a certain packet
  enabled: true
  # Amount of un-received packets to flag suspicion of a player timing out
  total_packets: 40
  # Amount of client ticks to pass by before kicking the player for timing out (10 seconds / 200 ticks by default - like in MC Java and RakNet)
  ticks: 200

banwaves:
  # Choose if banwaves should be enabled on your server
  enabled: false
  # Total violations someone should be added to a ban-wave
  violations: 40
  # Length in days to ban the player for, leave as "p" for permanent
  ban_length: 7
  # Message for when the ban-wave starts
  start_message: "§eThe ban wave has §6commenced"
  # Message to broadcast when a player is banned in the ban-wave
  ban_message: "§g{player} §ehas §6been §ebanned in the ban wave §7[Wave {id}]"
  # Message to broadcast when the ban wave has concluded
  end_message: "§eThe ban wave has §6concluded§e - remember to play legit!"

webhook:
  # Link to the webhook (leave as none to keep webhook functionality disabled)
  link: none
  # If alerts should be sent in webhook messages
  alerts: false
  # If punishments should be sent in webhook messages
  punishments: false

detections:
  # Autoclicker detections
  Autoclicker:
    A:
      enabled: true
      punishment_type: none
      max_vl: 5
      code: Noah
      max_cps: 21
    B:
      enabled: true
      punishment_type: none
      max_vl: 3
      code: Crocodile
      samples: 10
      max_duplicates: 4
  # Aim detections
  Aim:
    A:
      enabled: true
      punishment_type: none
      max_vl: 5
      code: Neck
    B:
      enabled: true
      punishment_type: none
      max_vl: 5
      code: Hawkeye
  # Killaura detections
  Killaura:
    A:
      enabled: true
      punishment_type: none
      max_vl: 5
      code: Lancelot
    B:
      enabled: true
      punishment_type: none
      max_vl: 10
      code: Inkingmistake
  # Range checks
  Range:
    A:
      enabled: true
      punishment_type: none
      max_vl: 20
      max_raw: 3.05
      max_dist: 3.01
      code: Aristotle
  # Fly detections
  Fly:
    A:
      enabled: true
      punishment_type: none
      max_vl: 20
      code: Albatross
      diff_max: 0.015
      setback: true
    B:
      enabled: true
      punishment_type: none
      max_vl: 20
      code: Hummingbird
      diff_max: 0.01
      setback: true
    C:
      enabled: true
      punishment_type: none
      max_vl: 2
      code: Blackhawk
      setback: true
  # Motion detections
  Motion:
    A:
      enabled: true
      punishment_type: none
      max_vl: 10
      code: Mach1
      setback: true
    B:
      enabled: true
      punishment_type: none
      max_vl: 10
      code: Mach2
      setback: true
    C:
      enabled: true
      punishment_type: none
      max_vl: 10
      code: Mach3
      setback: true
    D:
      enabled: true
      punishment_type: none
      max_vl: 10
      code: Mach4
      setback: false
  # Phase detections
  Phase:
    A:
      enabled: true
      punishment_type: none
      max_vl: 20
      code: Ghost
      setback: false
  # Velocity detections
  Velocity:
    A:
      enabled: true
      punishment_type: none
      max_vl: 20
      code: Hypersonic
      pct: 99.99
    B:
      enabled: false
      punishment_type: none
      max_vl: 20
      code: Lightspeed
  # EditionFaker detections
  EditionFaker:
    A:
      enabled: true
      punishment_type: kick
      max_vl: 1
      code: Janus
  # Packet detections
  Packets:
    A:
      enabled: true
      punishment_type: kick
      max_vl: 1
      code: BP1
    B:
      enabled: true
      punishment_type: kick
      max_vl: 10
      code: MPP
    C:
      enabled: true
      punishment_type: kick
      max_vl: 2
      code: JPPM
  # Timer detections
  Timer:
    A:
      enabled: true
      punishment_type: kick
      max_vl: 5
      code: Paradox